import type { FireState } from '../../../types/fire/models/FireState';
import { FIRE_CONSTANTS }  from './fireConfig';

/** Weighted average annual return across ETF and cash (for wealth projection). */
export function calcWeightedReturn(state: FireState): number {
  const total = state.etfBalance + state.cashBalance;
  if (total === 0) return FIRE_CONSTANTS.ANNUAL_RETURN;
  return (
    state.etfBalance  * (state.etfRate  / 100)
    + state.cashBalance * (state.cashRate / 100)
  ) / total;
}

/** Annual asset income generated by the portfolio at a given value. */
export function calcAssetIncome(portfolioValue: number, weightedReturn: number): number {
  return portfolioValue * weightedReturn;
}
