import type { FireState } from '../../../../types/fire/models/FireState';
import { FIRE_CONSTANTS }  from '../fireConfig';

export function calcNetWorth(state: FireState): number {
  return state.etfBalance + state.cashBalance + state.cryptoBalance;
}

export function calcGrossSWR(netWorth: number): number {
  return (netWorth * FIRE_CONSTANTS.SWR_RATE) / 12;
}

/** Weighted average annual return across all asset classes (as a decimal, e.g. 0.07). */
export function calcWeightedReturn(state: FireState): number {
  const total = state.etfBalance + state.cashBalance + state.cryptoBalance;
  if (total === 0) return FIRE_CONSTANTS.ANNUAL_RETURN;
  return (
    state.etfBalance    * (state.etfRate    / 100)
    + state.cashBalance * (state.cashRate   / 100)
    + state.cryptoBalance * (state.cryptoRate / 100)
  ) / total;
}

/** Annual income generated by all assets at a given portfolio value. */
export function calcAssetIncome(portfolioValue: number, weightedReturn: number): number {
  return portfolioValue * weightedReturn;
}
